import streamlit as st
import random

# --- Callsign dictionary ---
callsigns = {
    "AAB": "Abelag", "AAF": "Aigle Azur", "AAL": "American", "AAR": "Asiana",
    "ABN": "Air Albania", "ACA": "Air Canada", "AIC": "Air India",
    "AFR": "Air France", "AZA": "Alitalia", "ASL": "Air Serbia",
    "ATL": "Air Bernina", "AUA": "Austrian", "AUI": "Ukraine International",
    "AVA": "Avianca", "AZW": "Air Zimbabwe", "BAF": "Belgian Airforce",
    "BAW": "Speedbird", "BEL": "City Bird", "BER": "Air Berlin",
    "BMS": "Blue Messenger", "BTI": "Air Baltic", "BUL": "Bulgarian Charter",
    "BVR": "Bavarian", "CAL": "China Airlines", "CCA": "Air China",
    "CES": "China Eastern", "CSN": "China Southern", "CFG": "Condor",
    "CPA": "Cathay", "CYP": "Cyprus", "CLX": "Cargolux", "DAH": "Air Algerie",
    "DAL": "Delta", "DLH": "Lufthansa", "DSO": "Dassault", "DUB": "Dubair",
    "DNM": "Dan Air", "EAT": "Trans Europe", "ELY": "El Al", "ETD": "Etihad",
    "EZY": "Easyjet", "FIN": "Finnair", "FIA": "Finnish Air Force",
    "FTH": "First Flight", "FDX": "Fedex", "GEC": "Lufthansa Cargo",
    "GFA": "Gulf Air", "GLG": "Gill Airways", "GTI": "Grandstar Cargo",
    "GWI": "Germanwings", "HAL": "Hawaiian", "HLX": "Hapag Lloyd",
    "HVN": "Vietnam Airlines", "HOP": "HOP!", "IBE": "Iberia",
    "IAW": "Iraqi Airways", "IRA": "Iran Air", "IRZ": "Mahan Air",
    "ITY": "ITA Airways", "JAF": "Beauty", "JAL": "Japan Air",
    "JBU": "Jet Blue", "JAI": "Jet Airways", "JTG": "Jet Time",
    "KAC": "Kuwait", "KAL": "Korean Air", "KLM": "KLM", "LOT": "LOT",
    "LDA": "Lauda Motion", "LGL": "Luxair", "LZB": "Flying Bulgaria",
    "LXR": "Lux Rescue", "MAH": "Malev", "MAS": "Malaysian",
    "MEA": "Cedar Jet", "MSR": "Egyptair", "MSX": "Egyptair Cargo",
    "MPH": "Martinair", "MON": "Monarch", "MNB": "Black Sea",
    "NAX": "Norwegian", "NJE": "Fraction", "NLY": "Nile Bird",
    "NVR": "Novair", "OAL": "Olympic", "OHY": "Onur Air",
    "OSY": "Open Skies", "OTF": "OrangeSky", "PIA": "Pakistan",
    "PGT": "SunTurk", "PBD": "Pobeda", "PRI": "Primera",
    "PWF": "Private Wings", "QAF": "Amiri", "QFA": "Qantas",
    "QTR": "Qatari", "QGA": "Quadax", "RAM": "Royalair Maroc",
    "RAA": "Rada", "ROU": "Rouge", "RYR": "Ryanair",
    "RWD": "RwandAir", "SAS": "Scandinavian", "SBI": "Siberian",
    "SDM": "Rossiya", "SIA": "Singapore", "SWR": "Swiss",
    "SVR": "Sverdlovsk", "TAM": "Tamazi", "THA": "Thai",
